
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ladin
 */
public class GUI extends javax.swing.JFrame {
FondoPanel fondo = new FondoPanel();
int numero;
int moneda=20;
    
    public void metodo(){
        int slot1 = (int)(Math.random()*9+1);
        int slot2 = (int)(Math.random()*9+1);
        int slot3 = (int)(Math.random()*9+1);
        posicion1.setText(String.valueOf(slot1));
        posicion2.setText(String.valueOf(slot2));
        posicion3.setText(String.valueOf(slot3));
        
        if (slot1 == slot2 && slot2==slot3){
            switch(slot1){
                case 7:
                    moneda +=10;
                    JOptionPane.showMessageDialog(this, "¡¡¡¡¡GANASTE 20 MONEDAS!!!!!");
                    break;
                    
                default:
                    moneda += 5;
                    JOptionPane.showMessageDialog(this, "¡¡¡¡¡GANASTE 5 MONEDAS!!!!!");
                    break;
            }
        }

        monedas.setText("MONEDAS "+String.valueOf(moneda));
       
        if (moneda==0){
            
            numero = JOptionPane.showConfirmDialog(this, "¿QUIERES JUGAR DE NUEVO?", "TRAGA MONEDAS",JOptionPane.YES_NO_OPTION);
        
        if (numero==0) {
            moneda=20; 
            monedas.setText("MONEDAS "+String.valueOf(moneda));
        } else {
            System.exit(0);
        }
        }
    }
    public GUI() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        btJugar = new javax.swing.JButton();
        posicion1 = new javax.swing.JLabel();
        posicion2 = new javax.swing.JLabel();
        posicion3 = new javax.swing.JLabel();
        monedas = new javax.swing.JLabel();
        btJugar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("TRAGA MONEDAS");

        btJugar.setBackground(new java.awt.Color(255, 255, 0));
        btJugar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btJugar.setText("JUGAR");
        btJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugarActionPerformed(evt);
            }
        });

        posicion1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        posicion1.setForeground(new java.awt.Color(153, 153, 153));
        posicion1.setText("3");

        posicion2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        posicion2.setForeground(new java.awt.Color(153, 153, 153));
        posicion2.setText("6");

        posicion3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        posicion3.setForeground(new java.awt.Color(153, 153, 153));
        posicion3.setText("9");

        monedas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        monedas.setForeground(new java.awt.Color(153, 153, 153));
        monedas.setText("MONEDAS 2.0");

        btJugar1.setBackground(new java.awt.Color(255, 0, 0));
        btJugar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btJugar1.setText("SALIR");
        btJugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJugar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(monedas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(posicion2)
                        .addGap(101, 101, 101)
                        .addComponent(posicion3)
                        .addGap(77, 77, 77))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btJugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btJugar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monedas)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicion1)
                    .addComponent(posicion3)
                    .addComponent(posicion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btJugar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btJugar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugarActionPerformed
       
        moneda -=1;
        monedas.setText("MONEDAS "+String.valueOf(moneda));
        
        Thread hilo = new Thread();
        metodo();
        hilo.start();
       
        
        

    }//GEN-LAST:event_btJugarActionPerformed

    private void btJugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJugar1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btJugar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJugar;
    private javax.swing.JButton btJugar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monedas;
    private javax.swing.JLabel posicion1;
    private javax.swing.JLabel posicion2;
    private javax.swing.JLabel posicion3;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        
        public void pain(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Fondos/money.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
